export const PROFILE_FETCHED = 'PROFILE_FETCHED';
export const PRODUCT_CODE = 'PRODUCT_CODE';
export const LOOKBOOK_SELECTED = 'LOOKBOOK_SELECTED';
export const PRODUCTS_SELECTED = 'PRODUCTS_SELECTED';

